name: toolbox
description: "My personal toolbox app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  http: ^1.2.1
  auto_size_text: ^3.0.0
  share_plus: ^9.0.0
  flutter_exit_app: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
